### ISSUE TITLE
Build with Typescript

### ISSUE THREAD

**Issue by rj254** [jeffijoe/yenv#13]
Using yenv with typescript results in the following message:

`node_modules/yenv/lib/yenv.d.ts(72,1): error TS2309: An export assignment cannot be used in a module with other exported elements.`

**Comment by jeffijoe** [comment]
Are you using v2 alpha?

**Comment by rj254** [comment]
Ah yes, that fixed it - I was on 2.0.0-rc.2

**Comment by jeffijoe** [comment]
Thanks for testing out the RC! 👍
