### ISSUE TITLE
Disable merging with process env variables

### ISSUE THREAD

**Issue by Akiyamka** [jeffijoe/yenv#17]
How I can disable adding all env variables from process in result?

**Comment by jeffijoe** [comment]
Pass in an empty `opts.envObject`

**Comment by Akiyamka** [comment]
Awesome, thanks! Can I create MR for adding this info in readme?

**Comment by jeffijoe** [comment]
Go for it 😀

**Comment by Akiyamka** [comment]
Added in #18
