### ISSUE TITLE
ReferenceError: [yenv] SETTING not found in the loaded environment

### ISSUE THREAD

**Issue by Arcanorum** [jeffijoe/yenv#22]
I keep getting this error with this lib.

> ReferenceError: [yenv] TEST not found in the loaded environment

My settings.yml file
`TEST: stuff`

My code:
```js
const yenv = require("yenv");
const env = yenv("settings.yml");
console.log("test?", env.TEST);
```

Latest version.
Ubuntu 20.

**Comment by jeffijoe** [comment]
The top-level objects in the `env.yaml` represent the **environment**.

```yml
development:
  TEST: stuff
