### ISSUE TITLE
How to use it with typescript?

### ISSUE THREAD

**Issue by jsplate** [jeffijoe/yenv#25]
As stated in the documentation the variable can be imported by `import * as yenv from 'yenv'.`

But how to use it then?

`const env = yenv('env.yaml', { env: 'production' })`

is not possible in typescript because yenv then is not callable.

So how to initialize and use it?
A short one- or twoliner would be great!

**Comment by jeffijoe** [comment]
I think its just `import yenv from ‘yenv’` now, might need to update docs 😅
