### ISSUE TITLE
Update yargs dependency

### ISSUE THREAD

**Issue by joeylgutierrez** [jeffijoe/yenv#31]
"yargs": "^16.2.0" needs to be updated to the latest yargs@17.2.1 to remove a high snyk security issue

`✗ Regular Expression Denial of Service (ReDoS) [High Severity][https://snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908] in ansi-regex@5.0.0
    introduced by yenv@3.0.0 > yargs@16.2.0 > string-width@4.2.2 > strip-ansi@6.0.0 > ansi-regex@5.0.0 and 4 other path(s)
  This issue was fixed in versions: 6.0.1, 5.0.1`

**Comment by jeffijoe** [comment]
Released as 3.0.1.
