### ISSUE TITLE
yenv CLI feature request: specify env for command

### ISSUE THREAD

**Issue by sauntimo** [jeffijoe/yenv#36]
yenv is great, I really like the composability - thanks for all your work on it!

It would be neat if there was a way of using it like [dotenv-cli](https://github.com/entropitor/dotenv-cli) which allows you to specify env in an npm script, for instance `dotenv -e .env.test -- jest`. Currently if I want to use `dotenv-cli` as well as yenv for this purpose, I'd end up with my variables repeated across two files which seems like it would be complex to manage. If anyone has an elegant solution to this, I would be very interested. Similarly if you're interested in a PR along those lines, I could maybe see what I could do...

Previously I was using `dotenv` but it doesn't support multiple env files and I needed to add a test env with different db connection details from my development env.

**Comment by jeffijoe** [comment]
Why not just use `NODE_ENV=test jest`? That’s been working for me.

**Comment by sauntimo** [comment]
See this is very sensible suggestion and I'm not sure why it didn't occur to me... 🤦 I'm running into issues with how Prisma manages environment variables (see [docs](https://www.prisma.io/docs/guides/development-environment/environment-variables)) but that's clearly out of scope here, so I'll close this. I think this should work fine in other contexts. Thanks for your help!
