### ISSUE TITLE
Normalize preprocessor symbols.

### ISSUE THREAD

**Issue by jeffijoe** [jeffijoe/yenv#6]
`compose` is a way to merge one section into another, but if the user by any chance expects an environment variable to be called `compose`, they're screwed.

Maybe we should prepend a symbol to the built-in preprocessors, so `compose` becomes `~compose`?

If this does happen, it'll be a major version bump.

**Comment by ddproxy** [comment]
👍

**Comment by jeffijoe** [comment]
This was done in 1.0. Remember to update your yamls when updating, if you are using compose!
